### ISSUE TITLE
Bug: Quadzo-agugu should be Bizozogu

### ISSUE THREAD

**Issue by TallKite** [m-yac/xen-calc#10]
It's important that a temperament have only 1 name. And that the GCD of the higher primes be prominent in that name, because it helps indicate the pergen. The "grammar" is explained at
https://en.xen.wiki/w/Color_notation/Temperament_Names#Rules_for_naming_remote_colors

**Comment by m-yac** [comment]
This was a fun one to fix! Now, the algorithm for generating color symbols checks every possible way to pull out common factors and chooses the one which has the least number of hyphens, and if there's a tie, the most number of groupings (i.e. "bizogu" is chosen over "zozogugu"). This should get at the essence of what you're looking for in the linked page.

Let me know if you you find any issues with this new algorithm!

**Comment by TallKite** [comment]
I like the way you think! I will test it.
