### ISSUE TITLE
bug: bitwetho not twethotwetho

### ISSUE THREAD

**Issue by TallKite** [m-yac/xen-calc#18]
input 529/384, get twethotwetho 5th, should get bitwetho 5th

Zozo is preferred to bizo because it's simpler and clearer, and not any longer. But for primes > 19, the names are at least two syllables long, and bitwetho is better than twethotwetho because it's considerably shorter.

**Comment by m-yac** [comment]
Prime prefixes with p > 19 will now never get doubled in canonical color notation. Thanks!
