### ISSUE TITLE
Searching for edo scale degree intervals sometimes gives the wrong interval result page

### ISSUE THREAD

**Issue by lennartjansson** [m-yac/xen-calc#19]
For example, [searching for `5\12`](https://www.yacavone.net/xen-calc/?q=5%5C12) is currently giving what looks like the results page for `7\12`:

![Screenshot 2021-09-08 at 18-12-12 xen-calc 5 12](https://user-images.githubusercontent.com/15852255/132605853-0ebdeb39-1ea9-4f9d-a75b-aa8409c062b6.png)

This is not consistently broken -- for example, [searching for `10\12`](https://www.yacavone.net/xen-calc/?q=10%5C12) still gives the correct page.

I believe this is a recent regression since I remember this working pretty recently, like a week ago.

**Comment by m-yac** [comment]
Good catch, thanks for letting me know! This should be fixed now.

This bug was a result of a clash between verbose ups-and-downs notation and EDO step notation, the calculator was interpreting "5\12" as an interval like "up 5 \ 12" but without any ups or downs.
