### ISSUE TITLE
Feature request: isoharmonic complements

### ISSUE THREAD

**Issue by fredg999** [m-yac/xen-calc#2]
It could be useful to have a function that calculates the **upper and lower isoharmonic complement** of an interval (those are the terms that came up in the discussion on Discord with some members of the Xenharmonic Alliance). 

An [isoharmonic chord](https://en.xen.wiki/w/Isoharmonic_chords) contains pitches with the same frequency difference between any two successive pitches. It usually applies to just intonation chords (e.g. 4:5:6), but many propose to use the same term for irrational chords as well (e.g. 1:√3:2√3 − 1). Finding the isoharmonic complement allows one to build an isoharmonic chord out of any starting interval.

In general, for a given interval ratio _x_…
- the **upper isoharmonic complement** (shortened to iso-up or isoup) is the interval ratio _y_ such as 1:_x_:_y_ is an isoharmonic chord; therefore _y_ = 2_x_ − 1.
- the **lower isoharmonic complement** (shortened to iso-down or isodown) is the interval ratio _y_ such as _y_:1:_x_ is an isoharmonic chord; therefore _y_ = 2 − _x_ (only defined if _x_ ≥ 2, otherwise y ≤ 0).

The result should preferably be displayed in the same format as the input (e.g. cents in, cents out).

Here's an example in cents: isoup(400c) ≈ 324.70573549473977c

Please ask away if you have any questions about this. I hope you'll consider our request! :smile:

**Comment by m-yac** [comment]
Hi fredg, thanks for the suggestion! At the moment, there's a technical restriction to adding this, which is that xen-calc assumes all intervals have a prime factorization (AKA they have a [fractional monzo](https://en.xen.wiki/w/Fractional_monzo)). Intervals like 2sqrt(3)-1 = isoup(sqrt(3)) cannot be written in such a form, so they cannot be understood by xen-calc.

One option is to add this function, but make it only work for just ratios - e.g. isoup(5/4) = 6 but isoup(sqrt(3)) gives an error. If that would be enough for your use cases, I'm happy to add that.

Another option is to have it work exactly for just ratios as above, and approximately in all other cases - e.g. the equalities isoup(sqrt(3)) = 2^(1561.274101703268/1200) = 1561.274101703268c would hold exactly. This is less appealing to me, as one of my principles in designing xen-calc has been to avoid approximations wherever I can.

Yet another option is to allow xen-calc to accept intervals like 2sqrt(3)-1. This would just be a fair amount of work for me to refactor the code, but is doable. I think I would want to see a few other use cases of intervals like these (this is the first one I've found) or maybe a few other people interested in this feature before I'd consider making a change like this.

Thanks again for the interest, hope this helps.

**Comment by m-yac** [comment]
This has been added! I added isoUp(a) (solves 1 : a : ?), isoDown(a) (solves ? : 1 : a), and isoMid(a) (solves 1 : ? : a).

But more generally, I added support for that colon notation I just used, so for example you could write: [4 : 5 : 6 : ?](https://www.yacavone.net/xen-calc/?q=4+%3A+5+%3A+6+%3A+%3F) to find the interval which should go in the question mark. You can also replace all but two intervals with dashes (e.g. [4 : 5 : - : ?](https://www.yacavone.net/xen-calc/?q=4+%3A+5+%3A+-+%3A+%3F)), convenient for when the in-between intervals don't have closed forms in xen-calc (e.g. [1 : ? : - : sqrt(5)](https://www.yacavone.net/xen-calc/?q=1+%3A+%3F+%3A+-+%3A+sqrt%285%29)).

For more context, your argument about "a calculator with no π key" was tremendously convincing! I also realized that the golden ratio is [1 : ? : sqrt(5)](https://www.yacavone.net/xen-calc/?q=1+%3A+%3F+%3A+sqrt%285%29), which made me more interested in these types of intervals. In the end I was able to figure out a way to allow imprecision into the calculator that was usually reversible in simple cases (e.g. [1 : phi : ?](https://www.yacavone.net/xen-calc/?q=1+%3A+phi+%3A+%3F) is exactly sqrt(5)!) and didn't involve that much work for me.

I think the calculator is much more useful having made these changes. Thanks again for the suggestion!

Before I close this issue, I have a question. You seem to use the word "isoharmonic" to refer to chords with rational or irrational intervals, but the Xenharmonic wiki refers to the former as ["isoharmonic"](https://en.xen.wiki/w/Isoharmonic_chords) and the latter as ["linear"](https://en.xen.wiki/w/Linear_chord). I hedged my bets and used both names everywhere, but do you have any thoughts as to whether I should pick one or the other?

**Comment by fredg999** [comment]
Thank you very much! I'm glad to have been of any help.

The new features work just as expected, and even better so with the colon and dash notation. The noble mediant and isoMid functions also seem interesting in relation to all of this.

I think writing both "isoharmonic" and "linear" makes sense, since some people might be used to seeing just one or the other. I don't know much about it though, so maybe someone else will suggest otherwise eventually.

I'll be spreading the good news over at the XA Discord. ;) Thanks again for all of this!

**Comment by fredg999** [comment]
I found a few typos on the About page in the section about these new features. There are two tan boxes which don't link to the correct query page, although they show the correct text on the page:

- "1 : 5/4 : ?" points to "1 ? 5/4 ? ?"
- "? : 5 : 6" points to "? ? 5 ? 6"

Clicking on those tan boxes returns an error on the main page, since these are invalid expressions.

**Comment by m-yac** [comment]
Good catch, thanks! Those links should be fixed now.
