### ISSUE TITLE
Feature request: allow "1sn" as input for unison

### ISSUE THREAD

**Issue by TallKite** [m-yac/xen-calc#3]
enter ruyo 1sn, currently get a parse error, should get 15/14

related: enter ruyo 1st, currently get 15/14, maybe should get a "Did you mean ruyo 1sn?" message as well?

**Comment by m-yac** [comment]
Good catch, thanks! "1sn" as well as "8ve" are now supported. They are also now the default, e.g. clicking on "ruyo unison" on the page https://www.yacavone.net/xen-calc/?q=15/14 takes you to https://www.yacavone.net/xen-calc/?q=ruyo+1sn

I'm still pondering your suggestion about adding "did you mean" text (in this issue and in https://github.com/m-yac/microtonal-utils/issues/5), so I'm leaving this issue open.

**Comment by m-yac** [comment]
See #7.
