### ISSUE TITLE
Feature request: superscripts for repeated colors and magnitudes in concise color names

### ISSUE THREAD

**Issue by TallKite** [m-yac/xen-calc#4]
enter 250/243, currently get yyy1, should get y³1.

Two colors are OK, e.g. 25/24 = yy1 not y²1. Same rules should also apply to repeated L and s and c.

**Comment by m-yac** [comment]
Added in f1351047ddb309ee70bbd589625d06814203e1bc, e.g. https://www.yacavone.net/xen-calc/?q=c^3L^4zzzg^35
