### ISSUE TITLE
Bug: Absolute pitch features broken.

### ISSUE THREAD

**Issue by Kaiveran** [m-yac/xen-calc#6]
xen-calc seems completely unable to handle absolute pitch information after the latest update (i.e ones that would previously bring up the tuner dialog)

This includes one of the examples provided on the about page:
https://www.yacavone.net/xen-calc/?q=C4+where+A+%3D+432hz

And even lone notes:
https://www.yacavone.net/xen-calc/?q=F%E2%99%AF^5
https://www.yacavone.net/xen-calc/?q=A%E2%99%AE3

**Comment by Kaiveran** [comment]
In all three of these cases, there are different error messages on different platforms.

Windows 10 PC:
`Error: TypeError
res.intv is undefined`

Android Mobile:
`Error: TypeError
Cannot read property 'equals' of undefined`

**Comment by m-yac** [comment]
Thanks so much for letting me know about this! Note output should be fixed now.
