### ISSUE TITLE
Feature request: "Did you mean __?"

### ISSUE THREAD

**Issue by m-yac** [m-yac/xen-calc#7]
As brought up by @TallKite by  in #3 and https://github.com/m-yac/microtonal-utils/issues/5#issuecomment-890806820, it might be nice to show "Did you mean __?" text to the user in certain cases. The cases brought up so far are:
- Correcting "1st" to "1sn", "8th" to "8ve" (e.g. entering "ruyo 1st" and seeing "Did you mean ruyo 1sn?")
- Correcting hyphens in color notation (e.g. entering "coco-wa-9" and seeing "Did you mean cocowa9?")

**Comment by TallKite** [comment]
Why not make it standard procedure, after translating from the color name to a monzo, to then back-translate from that back to the color format, and see if that matches the input? You'd have to deduce the appropriate verbosity setting of course. Then if it doesn't match, throw a "Did you mean (back-translation)?" message.

**Comment by m-yac** [comment]
Done. I did exactly what you suggested, @TallKite, thanks!
