### ISSUE TITLE
Feature request: explanation of alternate meaning of "negative"

### ISSUE THREAD

**Issue by TallKite** [m-yac/xen-calc#9]
See https://en.xen.wiki/w/Talk:Color_notation#Incorrect_formula_for_converting_a_color_name.3F

**Comment by m-yac** [comment]
I will give a more complete response on the xen wiki, but I no longer feel any attachment to this alternate notation. So, the "descending"/"desc." prefix is now always used when converting to a color symbol, and the alternate notation in xen-calc's output has been removed.
